"""Stub leve do backend de processamento (GPU) para desenvolvimento local.

Expõe os MESMOS contratos de ai-podcast-clipper-backend/core/schemas.py
(ProcessVideoRequest/Response, DownloadYouTubeRequest/Response) — o arquivo é
copiado de lá no build (ver Dockerfile), não reimplementado à mão, pra não
divergir do contrato real. Não tem GPU/whisper/etc: só simula latência e uma
taxa de erro configuráveis via env var, o suficiente pra exercitar o
pipeline Next.js -> Inngest -> backend localmente com trace/log de ponta a
ponta.

NÃO é o backend real e não deve ser usado em produção.
"""

import os
import random
import time
import uuid

from fastapi import FastAPI, HTTPException
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

from otel_setup import setup_otel
from schemas import (
    DownloadYouTubeRequest,
    DownloadYouTubeResponse,
    ProcessVideoRequest,
    ProcessVideoResponse,
)

SERVICE_NAME = os.environ.get("OTEL_SERVICE_NAME", "ai-podcast-clipper-backend-stub")
setup_otel(SERVICE_NAME)

app = FastAPI(title="AI Podcast Clipper — Backend Stub (dev)")
# Instrumenta esta instância diretamente (temos o objeto `app` aqui, ao
# contrário do main.py real no Modal) — mais direto que depender só do
# monkeypatch global feito em setup_otel().
FastAPIInstrumentor.instrument_app(app)

LATENCY_MS_MIN = int(os.environ.get("STUB_LATENCY_MS_MIN", "200"))
LATENCY_MS_MAX = int(os.environ.get("STUB_LATENCY_MS_MAX", "1500"))
ERROR_RATE = float(os.environ.get("STUB_ERROR_RATE", "0"))  # 0.0 a 1.0


def _simulate_latency() -> None:
    delay_ms = random.uniform(LATENCY_MS_MIN, LATENCY_MS_MAX)
    time.sleep(delay_ms / 1000)


def _maybe_fail(context: str) -> None:
    if random.random() < ERROR_RATE:
        raise HTTPException(
            status_code=500,
            detail=f"Simulated failure in {context} (STUB_ERROR_RATE={ERROR_RATE})",
        )


@app.get("/")
def health_check():
    return {
        "status": "ok",
        "service": SERVICE_NAME,
        "latency_ms": [LATENCY_MS_MIN, LATENCY_MS_MAX],
        "error_rate": ERROR_RATE,
    }




@app.post("/process_video", response_model=ProcessVideoResponse)
def process_video(request: ProcessVideoRequest) -> ProcessVideoResponse:
    _simulate_latency()
    _maybe_fail("process_video")

    fake_clip = {
        "s3_key": f"clips/{uuid.uuid4().hex}/clip_1.mp4",
        "title": "Stub Clip",
        "hook": "This is a simulated clip from the local backend stub",
        "virality_score": random.randint(1, 10),
        "reason": "Generated by backend-stub for local observability testing",
        "start": 0.0,
        "end": 30.0,
    }

    return ProcessVideoResponse(
        success=True,
        file_id=request.s3_key,
        clips=[fake_clip],
    )


@app.post("/download_youtube", response_model=DownloadYouTubeResponse)
def download_youtube(request: DownloadYouTubeRequest) -> DownloadYouTubeResponse:
    _simulate_latency()
    _maybe_fail("download_youtube")

    s3_key = request.s3_key or f"youtube/{uuid.uuid4().hex}/original.mp4"

    return DownloadYouTubeResponse(
        success=True,
        s3_key=s3_key,
        title="Stub YouTube Video",
        duration=random.randint(30, 600),
        thumbnail=None,
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
